version: '3.9'

services:
  db:
    image: postgres:14.3
    container_name: ${DB_CONTAINER_NAME:-factuPro}
    profiles:
      - database
    restart: always
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-facturpro}
      POSTGRES_USER: ${DB_USERNAME:-facturpro}
      POSTGRES_DB: ${DB_NAME:-facturpro}
    volumes:
      - ${DB_DATA_PATH:-./postgres}:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${API_CONTAINER_NAME:-facturpro-api}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Asegura que la app use el servicio "db" del compose
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      DB_HOST: db
      DB_PORT: 5432
      DB_ENABLED: ${DB_ENABLED:-false}
      DB_MIGRATIONS_RUN: ${DB_MIGRATIONS_RUN:-false}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
